### ISSUE TITLE
workflow - remove C:\strawberry\lib from debug line

### ISSUE THREAD

**Issue by shawnlaffan** [carygravel/graphics-tiff#4]
https://github.com/carygravel/graphics-tiff/blob/39e4133d91e83ff70c23cc7ad8c9ea499428cff8/.github/workflows/windows.yml#L17

The third entry refers to ```C:\Strawberry\c\lib```, which looks to be what is throwing the error in the run.  

Although in looking further, the PowerShell ```ls``` command seems not to like multiple file names and paths.  I could be wrong, though.

**Comment by carygravel** [comment]
Yeah. I was trying to work out if the problem was paths in the gcc call not existing. `ls` is here mingw, not Powershell, I think, and it was failing because the path didn't exist.
